AllCops:
  Exclude:
    - config/initializers/secret_token.rb


#Metrics/AbcSize:
#  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 150

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Style/ClassVars:
  Enabled: false